// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args [0]);
		int higher = 0;
		int lower = 0;
		for (int i = 0; i <= n; i++) {
			double value = Math.random();
			if (value <= 0.5) lower++;
			else higher++;
		}
		System.out.println("> 0.5: " +higher);
		System.out.println("<= 0.5: " +lower);
		if (higher != 0 || lower != 0) System.out.println("Ratio: " +(double)higher/lower);
	}
}
